import Image from "next/image";
import CommonBtn from "./CommonBtn";

const Blogs = [
  {
    image: "/Image/blog/1250-gpm-fire-pump.webp",
    title: "1250 GPM Fire Pump | Z3 Corporation Fire Safety Solutions",
    slug: "1250 GPM Fire Pump",
    description:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
    article:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
  },
  {
    image: "/Image/blog/Best-Fire-Extinguisher-for-Home.webp",
    title: "1250 GPM Fire Pump | Z3 Corporation Fire Safety Solutions",
    slug: "1250 GPM Fire Pump",
    description:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
    article:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
  },
  {
    image: "/Image/blog/What-is-a-Fire-Rated-Door.webp",
    title: "1250 GPM Fire Pump | Z3 Corporation Fire Safety Solutions",
    slug: "1250 GPM Fire Pump",
    description:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
    article:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
  },
  {
    image: "/Image/blog/1250-gpm-fire-pump.webp",
    title: "1250 GPM Fire Pump | Z3 Corporation Fire Safety Solutions",
    slug: "1250 GPM Fire Pump",
    description:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
    article:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
  },
  {
    image: "/Image/blog/Best-Fire-Extinguisher-for-Home.webp",
    title: "1250 GPM Fire Pump | Z3 Corporation Fire Safety Solutions",
    slug: "1250 GPM Fire Pump",
    description:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
    article:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
  },
  {
    image: "/Image/blog/What-is-a-Fire-Rated-Door.webp",
    title: "1250 GPM Fire Pump | Z3 Corporation Fire Safety Solutions",
    slug: "1250 GPM Fire Pump",
    description:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
    article:
      "A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.A 1250 GPM fire pump provides critical high-volume performance for residential, corporate, and industrial buildings. Z3 Corporation offers expert installations and maintenance tailored to NFPA‑20 standards. In this guide, learn key details—including pump‑with‑controller catalogues, weight specs, and leading brands—to help you choose reliable fire safety solutions.",
  },
];

export default function () {
  return (
    <div>
      <div className="flex flex-wrap gap-15 lg:justify-between justify-center items-center">
        {Blogs.slice(3).map((blog, idx) => (
          <div key={idx} className="w-[350px] my-0 lg:my-26 shadow">
            <div className="relative h-[300px] w-[350px]">
              <Image
                src={blog.image}
                fill
                alt="Feature Image"
                className="ovject-contain"
              />
            </div>
            <div className="m-4 text-black space-y-4">
              <h1 className="line-clamp-2 overflow-hidden w-full text-lg font-bold">
                {blog.title}
              </h1>
              <h2 className="line-clamp-3">{blog.description}</h2>
              <CommonBtn text="Read more"/>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
